CREATE PROCEDURE IF NOT EXISTS Products()
BEGIN
    CREATE TABLE IF NOT EXISTS Products(
        Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL
        ,naam VARCHAR(255)  NOT NULL
        ,Barcode VARCHAR(255) NOT NULL                
        ,IsActive BIT NOT NULL DEFAULT 1
        ,Comments VARCHAR(255) NULL
        ,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;
END;